import { Red_Hat_Text } from "next/font/google";
import "./globals.css";

const redHatText = Red_Hat_Text({
  variable: "--font-red-hat-text",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Product list with cart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link
          rel="icon"
          href="/favicon/icon.png"
          type="image/png"
          sizes="32x32"
        />
      </head>
      <body className={`${redHatText.variable} antialiased`}>{children}</body>
    </html>
  );
}
